project:
  type: book
  output-dir: docs

book:
  title: "The Life of Saint Mary the Egyptian: Toward a Digital Critical Edition of the Old French Version T with English Translations"
  author: "Loren Easterday Lee"
  date: "04/22/2025"
  chapters:
    - index.qmd
    - abstract.qmd
    - acknowledgements.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2-1.qmd
    - chapter2-2.qmd
    - portraits.qmd
    - portraits-viz.qmd
    - chapter3.qmd
    - conclusion.qmd
    - appendix1.qmd
    - appendix2-intro.qmd
    - appendix2-T-A.qmd
    - appendix2-T-B.qmd
    - appendix2-T-C.qmd
    - appendix2-T-D.qmd
    - appendix2-T-E.qmd
    - appendix2-T-F1.qmd
    - appendix2-T-F2.qmd
    - references.qmd

bibliography: references.bib
csl: modern-language-association.csl

format:
  html:
    theme: cosmo
    number-sections: false
    toc: false
    css: styles.css
    grid:
      sidebar-width: 200px
      margin-width: 300px
    code-fold: true
    code-summary: "show the code"

  pdf:
    documentclass: scrreprt



