project:
  type: book
  output-dir: docs

book:
  title: "dissertation"
  author: "Loren Lee"
  date: "10/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4-Intro.qmd
    - chapter4-T-A.qmd
    - chapter4-T-B.qmd
    - chapter4-T-C.qmd
    - chapter4-T-D.qmd
    - chapter4-T-E.qmd
    - chapter4-T-F1.qmd
    - chapter4-T-F2.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    toc: false
    css: styles.css
    grid:
      sidebar-width: 200px
      margin-width: 300px
    code-fold: true
    code-summary: "show the code"

  pdf:
    documentclass: scrreprt



