project:
  type: book
  output-dir: docs

book:
  title: "dissertation"
  author: "Loren Lee"
  date: "10/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    css: styles.css
    code-fold: true
    code-summary: "show the code"

  pdf:
    documentclass: scrreprt



