project:
  type: book

book:
  title: "dissertation"
  author: "Loren Lee"
  date: "10/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    output-dir: docs
  pdf:
    documentclass: scrreprt



