project:
  type: book
  output-dir: docs

book:
  title: "The Life of Saint Mary the Egyptian: A Digital Critical Edition of the Old French Version T with English Translations"
  author: "Loren Easterday Lee"
  date: "03/05/2025"
  chapters:
    - index.qmd
    - abstract.qmd
    - acknowledgements.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4-1.qmd
    - chapter4-2.qmd
    - appendix-T-A.qmd
    - appendix-T-B.qmd
    - appendix-T-C.qmd
    - appendix-T-D.qmd
    - appendix-T-E.qmd
    - appendix-T-F1.qmd
    - appendix-T-F2.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    toc: false
    css: styles.css
    grid:
      sidebar-width: 200px
      margin-width: 300px
    code-fold: true
    code-summary: "show the code"

  pdf:
    documentclass: scrreprt



