---
title: "Acknowledgements"
---

Dissertations are a strange writing project. The first time you write one is likely the only time you will ever write one. And so, I’m particularly grateful for the guidance I’ve received from those who have been through this bizarre gauntlet themselves and from those whose expertise have been invaluable in my training. My director, Amy Ogden, has been a constant source of calm, nudging me gently forward and handling my unending delays with more patience than I have deserved. She has taught me both precision and balance, guiding me always to stay focused on what is most important and what serves. My mentors have all done their best with me and anything found lacking in this dissertation is my own fault.

The research of this dissertation was made possible by the support of the French Department, which in addition to providing my core graduate training also regularly supplied me with the additional funding necessary to conduct this research and attend conferences. It’s so rare to find an institution so full of people driven by passion for their work and genuine care for one another. I’m forever grateful to my colleagues — my friends — for their encouragement and their respect for a good *apéro*.

I must also extend my gratitude to the institutions that have greatly enriched my dissertation work. Rare Book School repeatedly sponsored my enrollment in their many amazing courses through the RBS-UVA Fellowship, giving me the skills necessary to work confidently with medieval manuscripts. The École Normale Supérieure provided me with both shelter and community in the heart of the *cinquième* as I conducted manuscript research at the BnF. The Société des Professeurs Français et Francophones d’Amérique Bourse Jeanne Marandon and the Chateaubriand Fellowship in Humanities and Social Sciences each generously supplied me with the income necessary to travel to numerous other special collections libraries in the pursuit of material that has informed this dissertation as well as given me enough material to comb over for years to come. Finally, UVA’s Scholar’s Lab granted me funding — via their Digital Humanities Fellowship — and community as I found my way back home to Virginia.

My family has been nothing but supportive, and despite their occasional incredulous questions — *When people ask me, what should I tell them you’re doing?* — , I’m spoiled by their concern for my happiness above all else. They have taught me hard work and common sense and everything worth knowing. In particular, I owe a great deal to my sister, Lindsay, who has blazed a trail for me in this world. It is thanks to her that I have any sense of adventure, and it is thanks to her that I pursued this digital project with any level of self-assurance. Since childhood, she’s shown me how to ‘play computer,’ and essentially, this dissertation amounts to a big grown-up version of playing computer. 

Finally, I don’t know what I would ever do without my person, Jared. He endures all my rants, believes in me even when I don’t, and forces me to remember the vital importance of having fun. Our daily walks with Maggie — a.k.a. “The Goose” — have helped to preserve my happiness and what’s left of my sanity. Thank you for putting up with me.
